version: '3'
volumes:
    share_code:
services:
    nginx:
        container_name: hintify-nginx
        image: nginx
        ports:
            - '80:80'
        links:
            - phpfpm
        volumes:
            #      - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/access.log:/var/log/nginx/access.log
            - ./docker/logs/error.log:/var/log/nginx/error.log
            - share_code:/var/www

    phpfpm:
        container_name: hintify-php
        build:
            context: .
            dockerfile: ./docker/phpfpm-production.docker
        image: hintify/php
        ports:
            - '9000:9000'
        volumes:
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - share_code:/var/www
#      - ./:/var/www
